### ISSUE TITLE
The latest code is not released found discrepancies

### ISSUE THREAD

**Issue by akash-work** [nrigaudiere/yarn-recursive#4]
The yarn-recursive.js in yarn-recursive module for 1.0.5 contains

let result = shell.exec(command);
shell.cd(directoryName);

but as per the latest changes seen on GitHub it is

shell.cd(directoryName);
let result = shell.exec(command);

Can the latest version be released soon?

**Comment by nrigaudiere** [comment]
@akash-work the `1.0.7` version has just been released, sorry for the delay :)
