### ISSUE TITLE
Feature request / assistance

### ISSUE THREAD

**Issue by nk2580** [nrigaudiere/yarn-recursive#5]
this package is great but when you use it on a monorepo it can be slow as the yarns are not run concurrently.

i'd like to spawn a process for each yarn that is discovered to speed up the CLI.

where would i find the collection of package.json files discovered?, from there i should be able to handle the rest of the pull request

**Comment by nrigaudiere** [comment]
Hi! Sorry for this (very) late reply!
The `packageJsonLocations` function called on line 39 returns all the paths for the package.json files :)
